# services:
#   postgres:
#     image: postgres
#     env_file:
#       - .env.local
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: password
#       POSTGRES_DB: predictascore
#     # Expose the Postgres port to the host machine,
#     # so you can inspect and administrate it
#     ports:
#       - "54320:5432"
#   pg_proxy:
#     image: ghcr.io/neondatabase/wsproxy:latest
#     environment:
#       APPEND_PORT: "postgres:5432"
#       ALLOW_ADDR_REGEX: ".*"
#       LOG_TRAFFIC: "true"
#     ports:
#       # Expose the WebSocket proxy port to the host machine,
#       # this is where @vercel/postgres will connect
#       - "54330:80"
#     depends_on:
#       - postgres

version: "3.8"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: predictascore
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
